### ISSUE TITLE
Adding Window support

### ISSUE THREAD

**Issue by jakirkham** [conda-forge/pyfftw-feedstock#2]
Would be nice to get a Windows package supported here. This contingent on having FFTW supported on Windows. ( https://github.com/conda-forge/fftw-feedstock/issues/2 )

**Comment by matmel** [comment]
Windows seems to be supported by FFTW package now (but see limitation of this issue conda-forge/fftw-feedstock#37 for python 3.6). Is there something else holding back windows support (except someone doing a pull request)?

**Comment by grlee77** [comment]
see my comment in conda-forge/fftw-feedstock#37 on why current pyFFTW is incompatible with conda-forge FFTW.  Hopefully with a new pyFFTW release, this will be resolved in the near future.

**Comment by ashwinvis** [comment]
There is some demand for a pyfftw windows build for python 3.6: pyFFTW/pyFFTW/issues/245. And some other folks have managed to do it [for python 3.5 alone](https://anaconda.org/ccpi/pyfftw/). May I know if this would be possible soon?

**Comment by grlee77** [comment]
I had gotten this to work some time ago using the FFTW package that is available from conda-forge, but only when using the master branch of FFTW. The master branch is necessary because it enables some new environment variables to help pyFFTW find the libraries and it supports having only float and double precision available (conda-forge currently does not provide the long double variant of FFTW on windows).

Ideally, we would make a new pyFFTW release and then a PR here rather than building a package from master. I think a release is basically ready to go at pyFFTW, so I just checked in again with the team over there about that (see pyFFTW/pyFFTW#187).

**Comment by ashwinvis** [comment]
Great news! For a fairly popular package such as pyFFTW a release has been long overdue :+1:

**Comment by grlee77** [comment]
closed by #23
